#https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
name: power-model
dependencies:
 - pandas 
 - numpy 
# - xlrd 
 - glpk
 - pyyaml
 pip:
   - otoole
