#AccumulatedAnnualDemand:
#    indices: [REGION,FUEL,YEAR,VALUE]
#    type: param
#    dtype: float
#    default: 0
AccumulatedNewCapacity:
    indices: [REGION,TECHNOLOGY,YEAR,VALUE]
    type: var
    dtype: float
AnnualEmissions:
    indices: [REGION,EMISSION,YEAR,VALUE]
    type: var
    dtype: float
AnnualTechnologyEmission:
    indices: [REGION,TECHNOLOGY,EMISSION,YEAR,VALUE]
    type: var
    dtype: float
CapitalInvestment:
    indices: [REGION,TECHNOLOGY,YEAR,VALUE]
    type: var
    dtype: float
#Demand: # TURNED OFF
#    indices: [REGION,TIMESLICE,FUEL,YEAR,VALUE]
#    type: var
#    dtype: float
#DiscountedCapitalInvestment: #not in fast?
#    indices: [REGION,TECHNOLOGY,YEAR,VALUE]
#    type: var
#    dtype: float
NewCapacity:
    indices: [REGION,TECHNOLOGY,YEAR,VALUE]
    type: var
    dtype: float
#RateOfActivity:
#    indices: [REGION,TIMESLICE,TECHNOLOGY,MODE_OF_OPERATION,YEAR,VALUE]
#    type: var
#    dtype: float
#RateOfProductionByTechnology:
#    indices: [REGION,TIMESLICE,TECHNOLOGY,FUEL,YEAR,VALUE]
#    type: var
#    dtype: float
#Production: # added to fast? # TURNED OFF
#    indices: [REGION,TIMESLICE,FUEL,YEAR,VALUE]
#    type: var
#    dtype: float
ProductionByTechnology:
    indices: [REGION,TIMESLICE,TECHNOLOGY,FUEL,YEAR,VALUE]
    type: var
    dtype: float
##ProductionAnnual: #added to fast
##    indices: [REGION,FUEL,YEAR,VALUE]
##    type: var
##    dtype: float
ProductionByTechnologyAnnual:
    indices: [REGION,TECHNOLOGY,FUEL,YEAR,VALUE]
    type: var
    dtype: float
#SpecifiedAnnualDemand:
#    indices: [REGION,FUEL,YEAR,VALUE]
#    type: param
#    dtype: float
#    default: 0
TotalCapacityAnnual:
    indices: [REGION,TECHNOLOGY,YEAR,VALUE]
    type: var
    dtype: float
TotalTechnologyAnnualActivity:
    indices: [REGION,TECHNOLOGY,YEAR,VALUE]
    type: var
    dtype: float
UseByTechnology:
    indices: [REGION,TIMESLICE,TECHNOLOGY,FUEL,YEAR,VALUE]
    type: var
    dtype: float
#UseAnnual: # need to add to osemosys_fast.txt
#    indices: [REGION,FUEL,YEAR,VALUE]
#    type: var
#    dtype: float
###EnergyBalanceEachYear4: # not in regular osemosys
###    indices: [REGION,YEAR,FUEL,VALUE]
###    type: equ
###    dtype: float