#AccumulatedAnnualDemand:
#    indices: [REGION,FUEL,YEAR,VALUE]
#    type: param
#    dtype: float
#    default: 0
AccumulatedNewCapacity:
    indices: [REGION,TECHNOLOGY,YEAR,VALUE]
    type: result
    dtype: float
    default: 0
    calculated: "True"
AnnualEmissions:
    indices: [REGION,EMISSION,YEAR,VALUE]
    type: result
    dtype: float
    default: 0
    calculated: "True"
AnnualTechnologyEmission:
    indices: [REGION,TECHNOLOGY,EMISSION,YEAR,VALUE]
    type: result
    dtype: float
    default: 0
    calculated: "True"
CapitalInvestment:
    indices: [REGION,TECHNOLOGY,YEAR,VALUE]
    type: result
    dtype: float
    default: 0
    calculated: "True"
#Demand: # TURNED OFF
#    indices: [REGION,TIMESLICE,FUEL,YEAR,VALUE]
#    type: result
#    dtype: float
#DiscountedCapitalInvestment: #not in fast?
#    indices: [REGION,TECHNOLOGY,YEAR,VALUE]
#    type: result
#    dtype: float
NewCapacity:
    indices: [REGION,TECHNOLOGY,YEAR,VALUE]
    type: result
    dtype: float
    default: 0
    calculated: "True"
#RateOfActivity:
#    indices: [REGION,TIMESLICE,TECHNOLOGY,MODE_OF_OPERATION,YEAR,VALUE]
#    type: result
#    dtype: float
#RateOfProductionByTechnology:
#    indices: [REGION,TIMESLICE,TECHNOLOGY,FUEL,YEAR,VALUE]
#    type: result
#    dtype: float
#Production: # added to fast? # TURNED OFF
#    indices: [REGION,TIMESLICE,FUEL,YEAR,VALUE]
#    type: result
#    dtype: float
ProductionByTechnology:
    indices: [REGION,TIMESLICE,TECHNOLOGY,FUEL,YEAR,VALUE]
    type: result
    dtype: float
    default: 0
    calculated: "True"
##ProductionAnnual: #added to fast
##    indices: [REGION,FUEL,YEAR,VALUE]
##    type: result
##    dtype: float
ProductionByTechnologyAnnual:
    indices: [REGION,TECHNOLOGY,FUEL,YEAR,VALUE]
    type: result
    dtype: float
    default: 0
    calculated: "True"
#SpecifiedAnnualDemand:
#    indices: [REGION,FUEL,YEAR,VALUE]
#    type: param
#    dtype: float
#    default: 0
TotalCapacityAnnual:
    indices: [REGION,TECHNOLOGY,YEAR,VALUE]
    type: result
    dtype: float
    default: 0
    calculated: "True"
TotalTechnologyAnnualActivity:
    indices: [REGION,TECHNOLOGY,YEAR,VALUE]
    type: result
    dtype: float
    default: 0
    calculated: "True"
UseByTechnology:
    indices: [REGION,TIMESLICE,TECHNOLOGY,FUEL,YEAR,VALUE]
    type: result
    dtype: float
    default: 0
    calculated: "True"
#UseAnnual: # need to add to osemosys_fast.txt
#    indices: [REGION,FUEL,YEAR,VALUE]
#    type: result
#    dtype: float
###EnergyBalanceEachYear4: # not in regular osemosys
###    indices: [REGION,YEAR,FUEL,VALUE]
###    type: equ
###    dtype: float