
# This file contains the values which are accpeted as fuel and technology names by the validation script from otoole. This should be kept up to date with fuel and technology names so that the validation script can make sure the model will run correctly.
codes:
  fuels:
    '17_electricity': Electricity (Generation)
    '17_electricity_Dx': Electricity (end use)
    '17_electricity_own': Own use
    '17_electricity_loss': Transmission losses
    '17_electricity_imports': Electricity imports
    '17_electricity_PV': Electricity from Solar PV
    '1_x_coal_thermal': Coal fuel
    '1_5_lignite': Coal fuel
    '2_coal_products': Coal fuel
    '7_7_gas_diesel_oil': Gas fuel
    '7_8_fuel_oil': Gas fuel
    '8_1_natural_gas': Gas fuel
    '8_1_natural_gas_CCS': Gas fuel
    '10_hydro': Hydro potential
    '11_geothermal': Geothermal potential
    '12_1_of_which_photovoltaics': Solar potential
    '14_wind': Wind potential
    '15_solid_biomass': Biomass fuel
    '16_others': Other fuels
  technologies:
    'POW_Coal_PP': Coal fuel
    'POW_Oil_PP': Gas fuel
    'POW_Gas_PP': Gas fuel
    'POW_Gas_CCS_PP': Gas fuel
    'POW_Hydro_PP': Hydro potential
    'POW_Geothermal_PP': Geothermal potential
    'POW_SolarPV_PP': Solar potential
    'POW_Wind_PP': Wind potential
    'POW_Solid_Biomass_PP': Biomass fuel
    'POW_Other_PP': Other fuels
    'POW_Transmission': Hydro potential
    'POW_TRN': Hydro potential
    'POW_IMPORT_ELEC_PP': Hydro potential
    'POW_TBATT': Hydro potential
    'POW_1_x_coal_thermal': Coal fuel
    'POW_1_5_lignite': Coal fuel
    'POW_2_coal_products': Coal fuel
    'POW_7_7_gas_diesel_oil': Gas fuel
    'POW_7_8_fuel_oil': Gas fuel
    'POW_8_1_natural_gas': Gas fuel
    'POW_8_1_natural_gas_CCS': Gas fuel
    'POW_10_hydro': Hydro potential
    'POW_11_geothermal': Geothermal potential
    'POW_12_1_of_which_photovoltaics': Solar potential
    'POW_14_wind': Wind potential
    'POW_15_solid_biomass': Biomass fuel
    'POW_16_others': Other fuels
    'POW_17_electricity_imports': Hydro potential
    'YYY_1_x_coal_thermal': Coal fuel
    'YYY_1_5_lignite': Coal fuel
    'YYY_2_coal_products': Coal fuel
    'YYY_7_7_gas_diesel_oil': Gas fuel
    'YYY_7_8_fuel_oil': Gas fuel
    'YYY_8_1_natural_gas': Gas fuel
    'YYY_8_1_natural_gas_CCS': Gas fuel
    'YYY_10_hydro': Hydro potential
    'YYY_11_geothermal': Geothermal potential
    'YYY_12_1_of_which_photovoltaics': Solar potential
    'YYY_14_wind': Wind potential
    'YYY_15_solid_biomass': Biomass fuel
    'YYY_16_others': Other fuels
    'YYY_17_electricity': Hydro potential
    'YYY_17_electricity_PV': Hydro potential
    'YYY_17_electricity_Dx': Hydro potential
    'YYY_17_electricity_own': Hydro potential
    'YYY_17_electricity_loss': Hydro potential
    'YYY_17_electricity_imports': Hydro potential
#Note that we have heavily simplified the schema in our model.
schema:
  FUEL:
  - name: fuel_name
      items:
      - name: fuels
      valid: fuels
      position: (1, 20) #i guess this is ok. assumes that no fuel name will be longer than 20 characters.
  TECHNOLOGY:
  - name: technology_name
      items:
      - name: three_letters #dont know the way to call it.
      valid: three_letters
      position: (1, 3)
      - name: fuels_or_techs
      valid: fuels_or_techs
      position: (4, 20)
#EXAMPLE VALIDATION FILE FROM OTOOLE GITHUB, NOT USED IN THIS MODEL. SEE https://otoole.readthedocs.io/en/latest/examples.html?highlight=schema#create-fuel-schema FOR REFERENCE. 
 
# codes:
#   fuels:
#     'WND': Wind
#     'COA': Coal
#     'ELC': Electricity
#   indetifiers:
#     '00': Raw Resource
#     '01': Intermediate
#     '02': End Use
#   techs:
#     'MIN': Mining
#     'PWR': Generator
#     'TRN': Transmission

# schema:
#   FUEL:
#   - name: fuel_name
#       items:
#       - name: fuels
#       valid: fuels
#       position: (1, 3)
#       - name: indetifiers
#       valid: indetifiers
#       position: (4, 5)
#   TECHNOLOGY:
#   - name: technology_name
#       items:
#       - name: techs
#       valid: techs
#       position: (1, 3)
#       - name: fuels
#       valid: fuels
#       position: (4, 6)